name: KanalD Scraper

on:
  workflow_dispatch: # Manuel çalıştırma butonu
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketleri yükle
        run: |
          pip install requests beautifulsoup4

      - name: Scripti çalıştır
        run: python kanald.py

      - name: HTML Dosyasını Artifact Olarak Yükle
        uses: actions/upload-artifact@v4
        with:
          name: kanald-video-liste
          path: kanald_library.html
          retention-days: 5 # 5 gün boyunca indirilebilir kalır
