name: NowTV Scraper

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 9 * * *' # Her gün Türkiye saatiyle 12:00'de otomatik çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketleri yükle
        run: |
          pip install requests beautifulsoup4 cloudscraper

      - name: Now TV Scriptini Çalıştır
        run: python nowtv.py

      - name: Değişiklikleri Repoya Yükle
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Sadece Now TV ile ilgili dosyaları ekle
          git add nowtv_vod.html
          
          # Değişiklik varsa commit ve push yap
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "🔄 Now TV Arşivi Güncellendi: $(date +'%d.%m.%Y %H:%M')"
            git push
          else
            echo "Değişiklik yok, atlanıyor."
          fi
